version: "3.8"

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: elastic_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: elastic_code_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - elastic_dev_network

  # Backend em modo desenvolvimento
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: development
    container_name: elastic_backend_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/elastic_code_dev
      JWT_SECRET: dev-jwt-secret-key
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - elastic_dev_network
    command: npm run start:dev

volumes:
  postgres_dev_data:
    driver: local

networks:
  elastic_dev_network:
    driver: bridge
